import React, { useState } from 'react';
import SectionHeading from '../components/SectionHeading';
import { ChevronDown, ChevronUp } from 'lucide-react';

const FAQ = () => {
  const faqs = [
    {
      question: 'How does Abun\'s AI content writer work?',
      answer: 'Abun uses advanced natural language processing (NLP) and machine learning algorithms to generate high-quality content. You simply provide a topic or brief, and our AI analyzes relevant data to create original, engaging content tailored to your needs. The system continuously learns from feedback to improve its outputs.'
    },
    {
      question: 'Is the content generated by Abun original and plagiarism-free?',
      answer: 'Yes, all content generated by Abun is original and plagiarism-free. Our AI creates unique content for each request, and we have built-in safeguards to ensure the output doesn\'t duplicate existing content. We also offer an optional plagiarism checker for additional peace of mind.'
    },
    {
      question: 'Can I customize the tone and style of the content?',
      answer: 'Absolutely! Abun allows you to specify the tone (professional, casual, conversational, etc.), style, and target audience for your content. You can also provide examples of writing you like, and our AI will adapt to match your preferred voice and style.'
    },
    {
      question: 'How much editing is needed after Abun generates content?',
      answer: 'Most users find that Abun\'s content requires minimal editing. The amount of editing needed depends on the complexity of your topic and specific requirements. Many users use the content as-is or with minor tweaks, while others use it as a solid first draft that they can refine and personalize.'
    },
    {
      question: 'Does Abun support multiple languages?',
      answer: 'Yes, Abun supports content generation in multiple languages including English, Spanish, French, German, Italian, Portuguese, Dutch, and more. Our AI is trained on diverse language datasets to ensure high-quality content regardless of the language you choose.'
    },
    {
      question: 'What types of content can Abun create?',
      answer: 'Abun can create a wide variety of content types including blog posts, articles, product descriptions, social media posts, email newsletters, ad copy, website content, and more. We offer specialized templates for different content formats to ensure optimal results.'
    },
    {
      question: 'How many words can I generate with my subscription?',
      answer: 'The word limit depends on your subscription plan. Our Starter plan includes 50,000 words per month, the Professional plan includes 200,000 words, and our Business plan offers unlimited words. Unused words don\'t roll over to the next month.'
    },
    {
      question: 'Can I cancel my subscription at any time?',
      answer: 'Yes, you can cancel your subscription at any time. There are no long-term contracts or cancellation fees. If you cancel, you\'ll continue to have access to Abun until the end of your current billing period.'
    }
  ];

  const [openIndex, setOpenIndex] = useState(0);

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? -1 : index);
  };

  return (
    <section id="faq" className="py-20 bg-white">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        <SectionHeading
          title="Frequently Asked Questions"
          subtitle="Find answers to common questions about Abun's AI content writing platform."
        />
        
        <div className="max-w-3xl mx-auto">
          <div className="space-y-4">
            {faqs.map((faq, index) => (
              <div key={index} className="border border-gray-200 rounded-lg overflow-hidden">
                <button
                  className={`w-full text-left p-5 flex justify-between items-center focus:outline-none ${
                    openIndex === index ? 'bg-primary-50' : 'bg-white'
                  }`}
                  onClick={() => toggleFAQ(index)}
                >
                  <span className="font-medium text-gray-900">{faq.question}</span>
                  {openIndex === index ? (
                    <ChevronUp className="h-5 w-5 text-primary-600 flex-shrink-0" />
                  ) : (
                    <ChevronDown className="h-5 w-5 text-gray-500 flex-shrink-0" />
                  )}
                </button>
                <div 
                  className={`overflow-hidden transition-all duration-300 ${
                    openIndex === index ? 'max-h-96' : 'max-h-0'
                  }`}
                >
                  <div className="p-5 pt-0 text-gray-600">
                    {faq.answer}
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          <div className="mt-12 text-center">
            <p className="text-gray-600 mb-2">Still have questions?</p>
            <a 
              href="#contact" 
              className="text-primary-600 font-medium hover:text-primary-700 transition-colors duration-300"
            >
              Contact our support team
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default FAQ;